version: '3.9'

networks:
  nginx_proxy:
    name: reverse_proxy

volumes:
  certs:
  dhparam:

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:0.9-alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - dhparam:/etc/nginx/dhparam
    networks:
      - nginx_proxy

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.test
      - VIRTUAL_PORT=8000
    networks:
      - nginx_proxy
